std_msgs/Header header
int64 id

px4_msgs/OffboardControlMode offboard_control_mode
px4_msgs/VehicleThrustSetpoint vehicle_thrust_setpoint
px4_msgs/VehicleTorqueSetpoint vehicle_torque_setpoint
    
#    /fmu/in/offboard_control_mode: px4_msgs/msg/OffboardControlMode
#    /fmu/in/vehicle_thrust_setpoint: px4_msgs/msg/VehicleThrustSetpoint
#    /fmu/in/vehicle_torque_setpoint: px4_msgs/msg/VehicleTorqueSetpoint
