px4_msgs/VehicleAngularVelocity vehicle_angular_velocity
px4_msgs/VehicleAttitude vehicle_attitude
px4_msgs/VehicleLocalPosition vehicle_local_position

# topics subscribed by the wrench mpc node
#/fmu/out/vehicle_angular_velocity: px4_msgs/msg/VehicleAngularVelocity
#/fmu/out/vehicle_attitude: px4_msgs/msg/VehicleAttitude
#/fmu/out/vehicle_local_position: px4_msgs/msg/VehicleLocalPosition
#/fmu/out/vehicle_status: px4_msgs/msg/VehicleStatus
